on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
            os: windows-2019
          - target: x86_64-unknown-linux-musl
            archive: tar.gz
            os: ubuntu-18.04
          - target: x86_64-apple-darwin
            archive: zip
            os: macos-11
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
      - run: cargo build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          with:
            name: akula_${{ matrix.os }}
            path: target/production/akula
